// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
let React = require('/Users/harry.northover/Repos/deno/node_modules/react');
let { Component } = React;
let ReactNative = require('/Users/harry.northover/Repos/deno/node_modules/react-native');
let { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function (appParameters) {
  AppRegistry.runApplication('deno', appParameters);
});
require('/Users/harry.northover/Repos/deno/index.android.js');
